//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWheelDeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class returncar
    {
        public int ReturnId { get; set; }
        public string CarNumber { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> Fine { get; set; }
        public Nullable<int> ElapsedDate { get; set; }
    }
}
