//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWheelDeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class returncar
    {
        public int id { get; set; }
        public string carno { get; set; }
        public Nullable<int> custid { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }
        public Nullable<int> fine { get; set; }
        public Nullable<int> elap { get; set; }
    }
}
